version: '3.8'

services:
  web:
    build: .
    command: gunicorn EcOMaaS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: ecomaas
        MYSQL_DATABASE: ecomaas
        MYSQL_USER: ecomaas
        MYSQL_PASSWORD: ecomaas
      volumes:
        - data:/var/lib/mysql
      ports:
        - "3306:3306"