# Generated by Django 4.1.13 on 2024-06-22 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudInit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cloud-init', max_length=255)),
                ('os', models.CharField(blank=True, default='ubuntu', max_length=8000)),
                ('userdata', models.TextField(blank=True, default='#cloud-config', max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='MaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAAS_HOST', models.CharField(max_length=255)),
                ('CONSUMER_KEY', models.CharField(max_length=255)),
                ('CONSUMER_TOKEN', models.CharField(max_length=255)),
                ('SECRET', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MaaS',
                'verbose_name_plural': 'MaaS',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Debian 12', max_length=255)),
                ('value', models.CharField(default='custom/debian-12', max_length=255)),
                ('storage_layout', models.TextField(default='flat', max_length=255)),
            ],
            options={
                'verbose_name': 'OS',
                'verbose_name_plural': 'OS',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servers', models.TextField(default='[]')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]